wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: reward_sender
      6:
      - 3
    - 1: reward_receiver
      6:
      - 3
    - 1: social_welfare
      6:
      - 3
    - 1: prob_of_signaling_1_when_bad
      6:
      - 3
    - 1: prob_of_signaling_1_when_good
      6:
      - 3
    - 1: prob_of_hiring_when_0
      6:
      - 3
    - 1: prob_of_hiring_when_1
      6:
      - 3
    python_version: 3.8.12
    start_time: 1681394277
    t:
      1:
      - 1
      3:
      - 7
      - 16
      - 18
      4: 3.8.12
      5: 0.12.11
      8:
      - 5
pro_objective_alpha:
  desc: null
  value: 1
