opts = {
    "game_nagents": 3,
    "game_action_space": 2,
    "game_action_space_total": 3,
    "game_comm_limited": True,
    "game_comm_bits": 1,
    "game_comm_sigma": 2,
    "nsteps": 6,
    "gamma": 1,
    "temp_min": 0.5,
    "anneal_rate": 0.0001,
    "use_gumbel": False,
    "rnn_size": 128,
    "bs": 32,
    "lr": 0.0005,
    "momentum": 0.05,
    "eps": 0.05,
    "nepisodes": 500,
    "step_test": 10,
    "step_target": 100,
    "eps_decay": 1.0
}
